### ISSUE TITLE
some props not responded

### ISSUE THREAD

**Issue by zek0** [brentN5/bt-target#4]
Thank you for script. I small have problem:

```
local atm = {
    `prop_atm_01`,
    `prop_atm_02`,
    `prop_atm_03`,
    `prop_fleeca_atm`,
506770882,
    }  
    AddTargetModel(atm, {
        options = {
            {
                event = "target:doatm",
                icon = "fas fa-share-square",
                label = "ATM",
            },
        },
        distance = 10.5
    })
```
In this case fleeca_atm not working, all another props work correctly.

**Comment by LiamDormon** [comment]
Please add code formatting, try using the actual hash of prop_fleeca_atm or GetHashKey("prop_fleeca_atm") rather than cfx hash notation

**Comment by zek0** [comment]
Thank for responding. Im test all combination. Many props work wondeful, this prop (prop_fleeca_atm) is problem.

**Comment by LiamDormon** [comment]
Many props work wondeful, this prop (prop_fleeca_atm) is problem.
That might be an issue you need to report to fivem if the raycast natives aren't working properly, there's nothing that I can see in this resource that would cause specific props to fail.
